CREATE DATABASE LINK "DBLOSFINNBANKLEA"
   CONNECT TO "FINNBANKLEA" 
   IDENTIFIED BY FINNBANKLEA
   USING '(DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 10.1.50.152)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = GDWiT1)
    )
  )';
